services:
  - type: web
    name: pib2-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false  # Debes configurarlo en el dashboard de Render
      - key: DB_USERNAME
        sync: false  # Debes configurarlo en el dashboard de Render
      - key: DB_PASSWORD
        sync: false  # Debes configurarlo en el dashboard de Render
      - key: jwt.secret
        generateValue: true  # Render generará un valor aleatorio seguro
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health

databases:
  - name: pib2-postgres
    plan: starter
    databaseName: pib2
    user: pib2user

